import React, { useState, useEffect } from "react";
import Head from "next/head";
import { collection, getDocs } from "firebase/firestore";

import ThemeWrapper from "../../components/ThemeWrapper";
import Navbar from "../../components/Navbar";
import styles from "../../styles/Leaderboard.module.css";
import { db } from "../../logic/firebase";
import LeaderboardUser from "../../components/LeaderboardUser";

export default function Main() {
  const [user, setUser] = useState(null);
  const [userData, setUserData] = useState(null);
  const [tradables, setTradables] = useState(null);

  useEffect(async () => {
    const user = JSON.parse(localStorage.getItem("weilai_user")) || null;
    const userData = JSON.parse(localStorage.getItem("weilai_data")) || null;
    setUser(user);
    setUserData(userData);

    if (!tradables) {
      let tradables_temp = [];
      const querySnapshot = await getDocs(collection(db, "users"));
      querySnapshot.forEach((doc) => {
        const tradable = doc.data();
        let score = 0;
        tradable.cards.map((card) => {
          const prob =
            (card.health * 1.5 + card.strength * 1.2 + card.intelligence * 1) /
            3.7;
          if (prob !== NaN || prob !== null || prob !== undefined || prob > 0) {
            score += 100 - prob;
          }
        });
        score /= tradable.cards.length;
        console.log(score);

        if (score !== NaN || score !== null || score !== undefined) {
          tradables_temp.push([score, tradable]);
        }
      });
      // console.log(tradables_temp);

      //Now sort the Data
      let arr = tradables_temp;
      for (var i = 0; i < arr.length; i++) {
        // Last i elements are already in place
        for (var j = 0; j < arr.length - i - 1; j++) {
          // Checking if the item at present iteration
          // is greater than the next iteration
          if (arr[j][0] > arr[j + 1][0]) {
            // If the condition is true then swap them
            var temp = arr[j];
            arr[j] = arr[j + 1];
            arr[j + 1] = temp;
          }
        }
      }
      // Print the sorted array
      console.log(arr);

      //Set the Data, finally
      //console.log(tradables_temp);
      tradables_temp = tradables_temp.reverse();
      for (let k = 0; k < tradables_temp.length; k++) {
        tradables_temp[k].push(k + 1);
      }
      setTradables(tradables_temp);
    }
  }, []);

  return (
    <ThemeWrapper>
      <Head>
        <title>Weilai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
          rel="stylesheet"
        />
      </Head>
      <div className="main_new">
        <Navbar user={user} />
        <div>
          <p className={styles.title}>Global Leaderboard</p>
          <hr style={{ marginTop: "-40px" }} />
          {tradables && (
            <>
              {tradables.map((e) => (
                <LeaderboardUser data={e} key={Math.floor(Math.random() * 1617)}/>
              ))}
            </>
          )}
        </div>
      </div>
    </ThemeWrapper>
  );
}
