import React, { useState, useEffect, useRef } from "react";
import Head from "next/head";

import ThemeWrapper from "../../components/ThemeWrapper";
import Navbar from "../../components/Navbar";
import Card from "../../components/Card";
import { cards } from "../../cards.config";

export default function Explanation() {
  const [user, setUser] = useState(null);
  const [userData, setUserData] = useState(null);
  const [ui, setUI] = useState(0);

  useEffect(async () => {
    //Boiler-Plate
    const user = JSON.parse(localStorage.getItem("weilai_user")) || null;
    const userData = JSON.parse(localStorage.getItem("weilai_data")) || null;
    setUser(user);
    setUserData(userData);
  }, []);
  return (
    <>
      <Head>
        <title>Login to Weilai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeWrapper>
        <div className="main_new">
          <Navbar user={user} />
          <div className="mainContent">
            {ui === 0 && (
              <>
                <img
                  src="https://media0.giphy.com/media/NxGZWHf4tHyyNsd9En/giphy.gif?cid=ecf05e47kqpmflfnorf9c6cvhx91r56g8l2ps537dg9r926t&rid=giphy.gif&ct=g"
                  width={"500px"}
                  className="jeff"
                />
                <div className="mainInfo">
                  <p className="title">This is Jeff!</p>
                  <p className="sub">He just created an account (like you). 👋</p>
                  <p className="sub">
                    <b>
                      When you create an account, you get 4 random cards ♠ ♦.
                    </b>
                  </p>
                  <p className="sub">
                    Not the playing kind, but like pokemon cards, with real
                    humans 👱🏼‍♂️
                  </p>
                  <p className="sub">
                    Each card has 3 stats : <b>Health ❤️</b>, <b>Strength 💪</b>
                    , and <b>Intelligence ✏️</b>
                  </p>
                  <p className="sub">Cards look like this :-</p>
                  <br />
                  <Card card={cards[0]} />
                  <br />
                  <button className="next_button" onClick={() => setUI(1)}>
                    Next
                  </button>
                </div>
              </>
            )}
            {ui === 1 && (
              <>
                <iframe
                  src="https://gifer.com/embed/7YyR"
                  width={"480px"}
                  height={"266.667px"}
                  frameBorder="0"
                  allowFullScreen
                  style={{ marginTop: "200px" }}
                  className="jeff"
                ></iframe>
                <div className="mainInfo">
                  <p className="title">Pretty Simple Right?</p>
                  <p className="sub">But like Takis, there's some spice 🌶️</p>
                  <p className="sub">
                    <b>
                      Every hour, all of the card's stats will get decreased by
                      one.
                    </b>
                  </p>
                  <p className="sub">
                    So if last hour your card had 70 health, it will have 69
                    now 😉.
                  </p>
                  <p className="sub">
                    <b>
                      To Prevent this, you can trade 🤝 your card for other
                      cards from
                    </b>
                  </p>
                  <p className="sub">
                    <b>
                      {" "}
                      other users to get the most out of your card before its
                      too late ⚰️.{" "}
                    </b>
                  </p>
                  <br />
                  <p className="sub">
                    The Goal is to collect Cards and get to the top of the
                    leaderboard 🏅
                  </p>
                  <p className="sub">
                    The clock's ticking, you better start soon!
                  </p>
                  <br />
                  <br />
                  <button
                    className="next_button"
                    onClick={() => window.location.replace("/auth/postregistration")}
                  >
                    End Tutorial
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      </ThemeWrapper>
      <style jsx>
        {`
          .mainContent {
            display: flex;
          }

          .mainInfo {
            display: flex;
            flex-direction: column;
          }

          .title {
            font-size: 2.3em;
            font-weight: 300;
          }

          .sub {
            margin-top: -10px;
            font-size: 1.5em;
            font-weight: 300;
          }

          .next_button {
            width: 160px;
            height: 50px;
            border-radius: 20px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 30px;
            margin-bottom: 20px;
            color: black;
            background-color: #00ff9d;
            font-weight: 600;
            font-size: 1.3em;
            font-family: "Poppins", sans-serif;
            outline: none;
            border: none;
            transition: all 500ms ease;
            cursor: pointer;
          }

          .next_button:hover {
            box-shadow: rgba(255, 255, 255, 0.35) 0px 5px 15px;
          }

          b {
            font-weight: 500;
          }

          @media only screen and (max-width: 600px) {
            .jeff{
              display:none;
              scale:0;
            }

            .title{
              padding-left:10px;
              text-size:2em;
            }

            .sub{
              padding-left:10px;
              text-size:1em;
            }
          }
        `}
      </style>
    </>
  );
}
