import React, { useState, useEffect } from "react";
import Head from "next/head";

import ThemeWrapper from "../../components/ThemeWrapper";
import Navbar from "../../components/Navbar";

export default function handshake() {
  const [user, setUser] = useState(null);
  const [userData, setUserData] = useState(null);

  useEffect(async () => {
    //Boiler-Plate
    const user = JSON.parse(localStorage.getItem("weilai_user")) || null;
    const userData = JSON.parse(localStorage.getItem("weilai_data")) || null;
    setUser(user);
    setUserData(userData);
  }, []);
  return (
    <>
      <div>
        <Head>
          <title>Login to Weilai</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ThemeWrapper>
          <div className="main_new">
            <Navbar user={user} />
            <div className="mainContent">
              <p className="title">Success!</p>
              <img
                src="https://acegif.com/wp-content/gifs/handshake-25.gif"
                className="image"
              />
              <p>
                Your Trade was a Success 🎉! Here's to another one in the
                future.
              </p>
              <button
                className="button"
                onClick={() => window.location.replace("/holdings/user")}
              >
                Go to Holdings
              </button>
            </div>
          </div>
        </ThemeWrapper>
      </div>
      <style jsx>
        {`
          .mainContent {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
          }
          .image {
            margin-top: -20px;
            width: 500px;
            height: 300px;
          }
          .title {
            margin-top: 0px;
            font-size: 3em;
          }
          .button {
            width: 250px;
            height: 50px;
            border-radius: 10px;
            color: black;
            background-color: white;
            font-weight: 300;
            font-size: 1em;
            font-family: "Poppins", sans-serif;
            outline: none;
            border: none;
            display: flex;
            align-items: center;
            justify-content: center;
            transition: all 300ms ease;
            cursor: pointer;
          }

          .button:hover {
            box-shadow: rgba(255, 255, 255, 0.35) 0px 5px 15px;
          }
        `}
      </style>
    </>
  );
}
