import React, { useState, useEffect } from "react";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import ThemeWrapper from "../components/ThemeWrapper";
import Navbar from "../components/Navbar";

export default function Home() {
  const [user, setUser] = useState(null);
  useEffect(() => {
    const user = JSON.parse(localStorage.getItem("weilai_user")) || null;
    setUser(user);

    if(!user){
      window.location.replace("/auth/login");
    }
    else if(user){
      window.location.replace("/marketplace");
    }
  }, [])
  return (
    <ThemeWrapper>
      <Head>
        <title>Weilai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
          rel="stylesheet"
        />
      </Head>

      <div className={styles.main}>
        <Navbar user={user}/>
      </div>
    </ThemeWrapper>
  );
}
